### ISSUE TITLE
Layout When Used with other Plugins

### ISSUE THREAD

**Issue by ryancasler** [j7126/OctoPrint-InlineConfirm#2]
Hi there.  Love the new Plug-In!!  Thank you so much!!!  This is really picky but you know what they say, if you don't ask, nothing will change.  So, I am wondering if the layout could be tweeked within Touch UI.  The cancel button ends up being below the other two buttons.  

![Screenshot_20210215-160356_Chrome](https://user-images.githubusercontent.com/30270489/107992975-de9d3b80-6fa7-11eb-9526-f645080a731e.jpg)

Also, when the Preheat Button plugin is enabled, it also does some odd things with the buttons.  

![image](https://user-images.githubusercontent.com/30270489/107993419-6420eb80-6fa8-11eb-8447-f68758923a02.png)

Don't know if anything can be done about that one but if it could and the fix is easy, that would be WONDERFUL.  Even if we had to manual tell the plugin that we had the others installed so it would know what to do, that would be fine.  If there isn't anything to be done, I understand.  Thanks again for the great plug-in!!!

**Comment by Willmac16** [comment]
I am not the plugin creator, but I did run into the behavior with preheat-button, and got 1 patch for that plugin merged and another patch to fix an issue with other buttons showing on top of the full width cancel is waiting to be merged into this plugin

**Comment by j7126** [comment]
@ryancasler I have released a patch which should fix these issues. 

It includes @Willmac16's fix for the preheat button issue and I have fixed the touch ui issue by detecting if touch ui is active and if so reverting back to the dialog confirmation (i will probably revisit this).

**Comment by ryancasler** [comment]
I don't think the issue with the Preheat Button Plugin is quite fixed yet.  

![image](https://user-images.githubusercontent.com/30270489/108001677-1bbef900-6fbb-11eb-90ec-06404be4b80d.png)


Re: Touch UI.  That definitely works.  At least I can use the plugin for my desktop UI.   Thanks for your quick action!!!

**Comment by j7126** [comment]
Hi @ryancasler, the fix for the preheat button plugin contains two components, a change within this plugin (which has been released in the update) and a change in the preheat button plugin which has been merged into source but not actually released yet. 

Due to this you will probably need to uninstall the preheat button plugin (there should be an option for uninstall and clean data or something like that) and then reinstall it. Please let me know if that fixes it for you.

**Comment by ryancasler** [comment]
I can confirm that after updating the Preheat button plugin everything is right with the world.  No need to clear data or anything.  Thanks for such a speedy response!!!
