### ISSUE TITLE
[Bug] - "Print" and "Cancel" Buttons combine/overlap

### ISSUE THREAD

**Issue by KenLucke** [j7126/OctoPrint-InlineConfirm#3]
When installed, my "Print" and "Cancel" buttons overlap and merge, and hide the Pause button.  They retain their individual functions, and the plugin functions as described, but cosmetically, there's a problem.  I thought it might be from Themeify, but disabling themes and customization does not cure it (see picture).  Other plugins that might be affecting it could be Dashboard and Widescreen.  I'll do some further investigations with these plugins disabled when I get a printer free again.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/57936294/108002645-1951a480-6fa5-11eb-9a26-29758d139e6b.png">

**Comment by j7126** [comment]
please see issue #2

**Comment by KenLucke** [comment]
> please see issue #2

Sorry, I only checked for open issues before duplicating something, you had already closed that one :)

The patch just released does indeed fix the issue (the new version also had not shown up at the time I posted).

**Comment by KenLucke** [comment]
BTW, it was Widescreen plugin that was the conflict.
