### ISSUE TITLE
Layout misaligned when using UI Customizer

### ISSUE THREAD

**Issue by MarloSM** [j7126/OctoPrint-InlineConfirm#5]
Hi, great plugin! It's made it much quicker to cancel failed prints.

I ran into an issue on mobile while using the UI Customizer plugin where the cancel button is lower and partially hidden. Is it possible to fix this issue?

![Screenshot_20210824-192734_Chrome](https://user-images.githubusercontent.com/22463469/130576634-1df3a54b-3e8a-4034-8190-0b7210728926.jpg)

**Comment by j7126** [comment]
I have released a new version which should fix this issue.
