### ISSUE TITLE
Cancel button misaligned, overlapping print button

### ISSUE THREAD

**Issue by HaLo2FrEeEk** [j7126/OctoPrint-InlineConfirm#6]
![image](https://user-images.githubusercontent.com/2855829/130724189-ea343b1a-aa32-48dd-a085-a4ef03f80e2c.png)

This is on Chrome browser on a PC. As you can see the cancel button is overlapping the print button. This started after the recent update.

Edit: Disabling the Preheat Button plugin restores normal layout for now, I'd rather not disable that plugin though.

**Comment by j7126** [comment]
I have just released an new update which should fix the issue.

**Comment by HaLo2FrEeEk** [comment]
Damn nice, that was quick. Thank you, that seems to have fixed it.
